package com.js.rbuddyapp;

import android.content.Context;
import android.content.Intent;

import com.google.android.gms.common.api.GoogleApiClient;
import com.js.android.IPhotoStore;
import com.js.rbuddy.IReceiptFile;
import com.js.rbuddy.Receipt;
import com.js.rbuddy.ReceiptFilter;
import com.js.rbuddy.TagSetFile;

/**
 * Methods that RBuddyActivity implements. This defines the methods that the
 * various fragments can call on the RBuddyActivity
 * 
 */
public interface IRBuddyActivity {

	void addListener(IRBuddyActivityListener listener);

	void removeListener(IRBuddyActivityListener listener);

	/**
	 * Get the active receipt
	 * 
	 * @return active receipt, or null if none selected
	 */
	Receipt getActiveReceipt();

	/**
	 * Request edit of active receipt's photo
	 */
	void editActiveReceiptPhoto();

	/**
	 * Notify activity that the active receipt has been edited (e.g.,
	 * ReceiptEditor calls this method to have ReceiptActivity refresh the
	 * receipt's appearance in the ReceiptList fragment)
	 */
	void activeReceiptEdited();

	/**
	 * Perform search (will later figure out how to indicate which search filter
	 * to use)
	 */
	void performSearch(ReceiptFilter filter);

	/**
	 * Specify active receipt
	 * 
	 * @param r
	 */
	void setActiveReceipt(Receipt r);

	/**
	 * Have activity process intent generated by Photo fragment
	 * 
	 * @param intent
	 */
	void processCapturePhotoIntent(Intent intent);

	/**
	 * Get list of receipt ids filtered according to search parameters
	 * 
	 * @return list of ids of receipts satisfying search criteria, or null if no
	 *         search active
	 */
	int[] getSearchResults();

	/**
	 * Dispose of any existing search results
	 */
	void clearSearchResults();

	/**
	 * Called when a connection to the cloud service (e.g. Google Drive) has
	 * been achieved
	 * 
	 * @param apiClient
	 */
	void connectedToServer(GoogleApiClient apiClient);

	/**
	 * Determine if we're to use the Google Drive API (for test purposes, we can
	 * disable this and use local storage only)
	 * 
	 * @return true if so
	 */
	boolean usingGoogleAPI();

	/**
	 * Get activity's context (for Activities, probably returns 'this')
	 * 
	 * @return
	 */
	Context getContext();

	IReceiptFile receiptFile();

	TagSetFile tagSetFile();

	IPhotoStore photoStore();

}
