package com.js.rbuddyapp;

import android.content.Intent;

import com.js.rbuddy.Receipt;
import com.js.rbuddy.ReceiptFilter;

/**
 * Methods that RBuddyActivity implements. This defines the methods that the
 * various fragments can call on the RBuddyActivity
 * 
 */
public interface IRBuddyActivity {

	void addListener(IRBuddyActivityListener listener);

	void removeListener(IRBuddyActivityListener listener);

	/**
	 * Get the active receipt
	 * 
	 * @return active receipt, or null if none selected
	 */
	Receipt getActiveReceipt();

	/**
	 * Request edit of active receipt's photo
	 */
	void editActiveReceiptPhoto();

	/**
	 * Notify activity that the active receipt has been edited (e.g.,
	 * ReceiptEditor calls this method to have ReceiptActivity refresh the
	 * receipt's appearance in the ReceiptList fragment)
	 */
	void activeReceiptEdited();

	/**
	 * Perform search (will later figure out how to indicate which search filter
	 * to use)
	 */
	void performSearch(ReceiptFilter filter);

	/**
	 * Specify active receipt
	 * 
	 * @param r
	 */
	void setActiveReceipt(Receipt r);

	/**
	 * Have activity process intent generated by Photo fragment
	 * 
	 * @param intent
	 */
	void processCapturePhotoIntent(Intent intent);

	/**
	 * Get list of receipt ids filtered according to search parameters
	 * 
	 * @return list of ids of receipts satisfying search criteria, or null if no
	 *         search active
	 */
	int[] getSearchResults();

	/**
	 * Dispose of any existing search results
	 */
	void clearSearchResults();

	void processGoogleApiConnected();
}
